# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            jtmpl
tagline:          'Succint front-end applications'
description:      ''
url:              http://jtmpl.com
baseurl:          /

author:
  name:           'Atanas Minev'
  url:            http://atmin.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/atmin/jtmpl

exclude:          node_modules
